エフェクト追加
Shi-553/RampageCars pull request #21
Opened 2022-03-07 13:49 UTC by Ren-Takeuchi

エフェクトのアセットとスクリプト追加

## Issueへのリンク
* https://github.com/Shi-553/RampageCars/issues/13

## やったこと
* デザイナーさんのアセット追加
* スクリプト追加
* 敵にあたった時のエフェクト追加

## やらないこと
* 

## その他
* 効果音は入れてない
* 爆発エフェクトはどこに入れればいいか？

2022-03-08 01:45 UTC, Shi-553 submitted a review, later dismissed

2022-03-08 02:49 UTC, Shi-553 requested changes
敵が死ぬときに爆発エフェクトつけてください。
ひとまずHitAudioクラスと同じように
`Invoke("メソッド名", 1);`
としてください。
あとでイベント使って書き換えます。

2022-03-08 06:57 UTC, Shi-553 commented
close #13

2022-03-08 17:19 UTC, Ren-Takeuchi commented
やったこと
当たった時とオブジェクトが消えたときにエフェクトを出すようにした。
Invoke();を使用し作成

2022-03-09 09:01 UTC, Shi-553 approved these changes

2022-03-09 09:01 UTC, merged