リセットボタンを追加しました。（キーボードの場合はP/パッドはstart）
Shi-553/RampageCars pull request #53
Opened 2022-03-16 11:28 UTC by momonga2525

## Issueへのリンク
* close #99（マージしたら自動で閉じる場合closeを付ける）

## やったこと
* このプルリクで何をしたのか？

## やらないこと
* このプルリクでやらないことは何か？（あれば。）

## その他
* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2022-03-17 04:19 UTC, Shi-553 commented
右上の・・・から編集できるのでお願いします

2022-03-17 04:27 UTC, Shi-553 requested changes

2022-03-17 04:27 UTC, Shi-553 commented on Assets/Cars/ICar.cs
> +        void GameReset();
リセットするのは車の機能じゃないので別スクリプトにしたほうがいいと思います。

2022-03-19 12:26 UTC, Shi-553 commented on Assets/Cars/ResetGame.cs
> +#if UNITY_EDITOR
QuitGameはエディタとビルド後で終了処理が違うから#ifを使ってる。
シーン遷移では単に`LoadScene`すればいいので27行目だけでいいです。

2022-03-19 12:26 UTC, Shi-553 commented on Assets/Cars/ResetGame.cs
> +#if UNITY_EDITOR
こっちも同じ

2022-03-19 13:46 UTC, momonga2525 commented
レビューありがとう！
変更してゲームリセット実装できました～

2022-03-19 13:54 UTC, Shi-553 approved these changes

2022-03-19 13:54 UTC, merged